ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000026A48357C10>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000026A483A7670>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000026A483AE0E0>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000025F7A373AF0>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000025F7A3C7550>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Error authenticating: HTTPSConnectionPool(host='api.rakuten-sec.co.jp', port=443): Max retries exceeded with url: /token (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000025F7A3CDFC0>: Failed to resolve 'api.rakuten-sec.co.jp' ([Errno 11001] getaddrinfo failed)"))
